### ISSUE TITLE
Event Attendees Value Truncated by Comma

### ISSUE THREAD

**Issue by bradley-holt** [ibm-watson-data-lab/advocated#4]
### Summary

When entering a comma in the number of event attendees, the value is truncated.

### Expected Behavior

When entering a value of "30,000" for the "Attendees" field on the "Attended" tab, the value stored should be "30000".

### Actual Behavior

When entering a value of "30,000" for the "Attendees" field on the "Attended" tab, the value stored is "30".

### Steps to Reproduce

1. Select the "Attended" tab
2. Enter the event data
3. Enter "30,000" for the value of the "Attendees" field
4. Click "Submit"
5. On the "Recent" tab, click the "edit" icon for the event record just entered
6. The value for the "Attendees" field is "30" and it should be "30000".

**Comment by glynnbird** [comment]
Turns out this is a JavaScript "feature":

```js
> var a = "30,000"
> parseInt(a)
30
```

It can be fixed in the code by removing the comma before parsing.

```js
> a = a.replace(/[^0-9\.]/g,'')
> parseInt(a)
30000
```

**Comment by glynnbird** [comment]
The attendees control was a textarea (cut-n-paste error) so it allowed commas in numbers. Numeric controls don't allow commas so you don't get parse errors further down the line.
